CREATE TABLE uf(
	cod_uf int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT uf_pkey PRIMARY KEY,
	sig_uf char(2) NOT NULL
);

CREATE TABLE cidade(
	cod_cid int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cid_pkey PRIMARY KEY,
	nome_cid varchar(64) NOT NULL,
	cod_uf int4 NOT NULL CONSTRAINT cod_uf_fkey REFERENCES uf(cod_uf)
);

CREATE TABLE endereco(
	cod_end int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT end_pkey PRIMARY KEY,
	cod_cid int NOT NULL CONSTRAINT cod_cid_fkey REFERENCES cidade(cod_cid),
	rua_end varchar(128) NOT NULL,
	numero_end int4 NOT NULL
);

CREATE TABLE modalidade(
	cod_mod int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cod_mod_pkey PRIMARY KEY,
	nome_mod varchar(128) NOT NULL,
	valor_mod decimal(10, 2),
	tam_mod int4 NOT NULL,
	horario_inicio_mod time NOT NULL,
	horario_fim_mod time NOT NULL
);

CREATE TABLE academia(
	cnpj_acad char(14) PRIMARY KEY,
	nome_acad varchar(200) NOT NULL,
	tel_acad varchar(15) NOT NULL,
	email_acad varchar(128),
	cod_end int4 NOT NULL CONSTRAINT cod_end_fkey REFERENCES endereco(cod_end)
);

CREATE TABLE instrutor(
	cpf_ins char(11) PRIMARY KEY,
	nome_ins varchar(128) NOT NULL,
	tel_ins varchar(15) NOT NULL,
	sexo_ins char(1) CONSTRAINT sexo_cins_chk CHECK (sexo_ins IN ('M', 'F')),
	cnpj_acad char(14) NOT NULL CONSTRAINT cnpj_acad_fkey REFERENCES academia(cnpj_acad),
	cod_end int4 NOT NULL CONSTRAINT cod_end_fkey REFERENCES endereco(cod_end)
);

CREATE TABLE cliente(
	cpf_cli char(11) PRIMARY KEY,
	nome_cli varchar(128) NOT NULL,
	tel_cli varchar(15) NOT NULL,
	sexo_cli char(1) CONSTRAINT sexo_cli_chk CHECK (sexo_cli IN ('M', 'F')),
	cnpj_acad char(14) NOT NULL CONSTRAINT cnpj_acad_fkey REFERENCES academia(cnpj_acad),
	cod_end int4 CONSTRAINT cod_end_fkey REFERENCES endereco(cod_end)
);

CREATE TABLE plano(
	cod_pla int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cod_pla_pkey PRIMARY KEY,
	tipo_pla char(1) NOT NULL CONSTRAINT tipo_pla_chk CHECK (tipo_pla IN ('M', 'T', 'S', 'A')),
	data_inicio_pla date NOT NULL,
	status_pla char(1) NOT NULL,
	valor_pla decimal(10, 2) NOT NULL,
	cpf_cli char(11) NOT NULL CONSTRAINT cpf_cli_fkey REFERENCES cliente(cpf_cli)
);

CREATE TABLE frequencia(
	cod_freq int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cod_freq_pkey PRIMARY KEY,
	data_freq timestamp DEFAULT current_timestamp,
	cpf_cli char(11) NOT NULL CONSTRAINT cpf_cli_fkey REFERENCES cliente(cpf_cli)
);

CREATE TABLE avaliacao_fisica(
	cod_af int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cod_af_pkey PRIMARY KEY,
	massa decimal(5, 2),
	altura decimal(3, 2),
	data_avaliacao timestamp DEFAULT current_timestamp,
	cpf_cli char(11) NOT NULL CONSTRAINT cpf_cli_fkey REFERENCES cliente(cpf_cli)
);

CREATE TABLE pagamento(
	cod_pag int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cod_pag_pkey PRIMARY KEY,
	metodo_pag char(1) NOT NULL CONSTRAINT metodo_pag_chk CHECK (metodo_pag IN ('C', 'D', 'P', 'B', 'F')),
	valor decimal(10, 2) NOT NULL,
	data_emissao_pag timestamp DEFAULT current_timestamp,
	data_quitacao_pag timestamp,
	status_pag char(1) NOT NULL CONSTRAINT status_pag_chk CHECK (status_pag IN ('P', 'Q', 'C')),
	cpf_cli char(11) NOT NULL CONSTRAINT cpf_cli_fkey REFERENCES cliente(cpf_cli),
	cnpj_acad char(14) NOT NULL CONSTRAINT cnpj_acad_fkey REFERENCES academia(cnpj_acad)
);

CREATE TABLE matricula(
	cod_mat int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cod_mat_pkey PRIMARY KEY,
	dat_mat timestamp DEFAULT current_timestamp,
	cod_mod int4 NOT NULL CONSTRAINT cod_mod_fkey REFERENCES modalidade(cod_mod),
	cod_pla int4 NOT NULL CONSTRAINT cod_pla_fkey REFERENCES plano(cod_pla)
);

CREATE TABLE supervisao(
	cod_sup int4 GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cod_sup_pkey PRIMARY KEY,
	cod_mod int4 NOT NULL CONSTRAINT cod_mod_fkey REFERENCES modalidade(cod_mod),
	cpf_ins char(11) NOT NULL CONSTRAINT cpf_ins_fkey REFERENCES instrutor(cpf_ins)
);