create table uf(
 cod_uf int4 generated by default as identity constraint uf_pkey primary key,
 sig_uf char(2) not null
);

create table cidade(
 cod_cid int4 generated by default as identity constraint cid_pkey primary key,
 nome_cid varchar(64) not null,
 cod_uf int4 not null constraint cod_uf_fkey references uf(cod_uf)
);

create table endereco(
 cod_end int4 generated by default as identity constraint end_pkey primary key,
 cod_cid int constraint cod_cid_fkey references cidade(cod_cid),
 rua_end varchar(128) not null,
 numero_end int4 not null
);

create table academia(
 cnpj_acad char(14) primary key,
 nome_acad varchar(200) not null,
 tel_acad varchar(15) not null,
 email_acad varchar(128),
 cod_end int4 constraint cod_end_fkey references endereco(cod_end)
);

create table cliente(
 cpf_cli char(11) primary key,
 nome_cli varchar(128) not null,
 tel_cli varchar(15) not null,
 sexo_cli char(1),
 cnpj_acad char(14) not null constraint cnpj_acad_fkey references academia(cnpj_acad),
 cod_end int4 constraint cod_end_fkey references endereco(cod_end)
);

create table frequencia(
 cod_freq int4 generated by default as identity constraint cod_freq_pkey primary key,
 data_freq timestamp default current_timestamp,
 cpf_cli char(11) not null constraint cpf_cli_fkey references cliente(cpf_cli)
);

create table avaliacao_fisica(
 cod_af int4 generated by default as identity constraint cod_af_pkey primary key,
 massa decimal(5, 2),
 altura decimal(3, 2),
 data_avaliacao timestamp default current_timestamp,
 cpf_cli char(11) not null constraint cpf_cli_fkey references cliente(cpf_cli)
);

create table instrutor(
 cpf_ins char(11) primary key,
 nome_ins varchar(128) not null,
 tel_ins varchar(15) not null,
 sexo_ins char(1),
 cnpj_acad char(14) not null constraint cnpj_acad_fkey references academia(cnpj_acad),
 cod_end int4 constraint cod_end_fkey references endereco(cod_end)
);

create table plano(
 cod_pla int4 generated by default as identity constraint cod_pla_pkey primary key,
 tipo_pla char(1) not null,
 data_inicio_pla date not null,
 status_pla char(1) not null,
 valor_pla decimal(10, 2) not null,
 cpf_cli char(11) not null constraint cpf_cli_fkey references cliente(cpf_cli)
);

create table pagamento(
 cod_pag int4 generated by default as identity constraint cod_pag_pkey primary key,
 metodo_pag varchar(64) not null,
 valor decimal(10,2) not null,
 data_emissao_pag timestamp default current_timestamp,
 data_quitacao_pag timestamp,
 status_pag char(1) not null,
 cod_pla int4 not null references plano(cod_pla)
);

create table modalidade(
 cod_mod int4 generated by default as identity constraint cod_mod_pkey primary key,
 nome_mod varchar(128) not null,
 valor_mod decimal(10, 2),
 tam_mod int4 not null,
 horario_inicio_mod time not null,
 horario_fim_mod time not null
);

create table matricula(
cod_mat int4 generated by default as identity constraint cod_mat_pkey primary key,
dat_mat timestamp default current_timestamp,
cod_mod int4 not null constraint cod_mod_fkey references modalidade(cod_mod),
cod_pla int4 not null constraint cod_pla_fkey references plano(cod_pla)
);

create table supervisao(
 cod_sup int4 generated by default as identity constraint cod_sup_pkey primary key,
 cod_mod int4 not null constraint cod_mod_fkey references modalidade(cod_mod),
 cpf_ins char(11) not null constraint cpf_ins_fkey references instrutor(cpf_ins)
);
